name: reviewdog
on:
  pull_request:
    branches: ["main", "develop"]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup-java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      # - name: Set up JDK 21
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: temurin
      #     java-version: 21

      # - name: Cache Maven packages
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.m2
      #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: ${{ runner.os }}-maven

      # - name: Build
      #   run: mvn clean install

      # - name: Run tests
      #   run: mvn test

      # - name: Upload Test Results
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-results
      #     path: create_employee/target/surefire-reports/
